# This is a basic workflow that is manually triggered

name: Archetype binder CI

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-compiler:
          - 18.x

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: install
      working-directory: ./check
      run: npm ci

    - name: init
      working-directory: ./check
      run: npm run init

    - name: mockup_init
      working-directory: ./check
      run: npm run mockup_init

    - name: test
      working-directory: ./check
      run: npm test:run
